name = "glailglind"
version = "1.1.3"
gleam = ">= 0.34.0"

description = "Gleam modules and functions for installing and invoking TailwindCSS"
licences = ["Apache-2.0"]
repository = { type = "github", user = "okkdev", repo = "glailglind" }

[dependencies]
gleam_stdlib = ">= 0.34.0 and < 2.0.0"
gleam_httpc = ">= 2.1.0 and < 3.0.0"
gleam_http = ">= 3.5.0 and < 4.0.0"
simplifile = ">= 2.0.0 and < 3.0.0"
tom = ">= 1.0.0 and < 2.0.0"
shellout = ">= 1.0.0 and < 2.0.0"
gleam_erlang = ">= 0.24.0 and < 2.0.0"

[dev-dependencies]
gleeunit = "~> 1.0"

[tailwind]
version = "3.4.1"
args = [
  "--config=tailwind.config.js",
  "--input=./test/input.css",
  "--output=./build/css/output.css",
]
