name = "gleam_tailwind"
version = "0.1.0"
gleam = ">= 0.32.0"

description = "Gleam modules and functions for installing and invoking TailwindCSS"
licences = ["Apache-2.0"]
repository = { type = "github", user = "okkdev", repo = "gleam_tailwind" }

[dependencies]
gleam_stdlib = "~> 0.32"
gleam_httpc = "~> 2.1"
gleam_http = "~> 3.5"
simplifile = "~> 1.0"
tom = "~> 0.2"
gleam_erlang = "~> 0.23"

[dev-dependencies]
gleeunit = "~> 1.0"

[tailwind]
version = "3.3.5"
args = [
  "--config=tailwind.config.js",
  "--input=./test/input.css",
  "--output=./build/css/output.css",
]
